### ISSUE TITLE
Difference between CRA and this?

### ISSUE THREAD

**Issue by saurav-bhagat** [dudiharush/react-deno-app-starter#3]
Is this starter even utilizing the benefits deno trying to provide?
For eg: Node_Modules, here Will we get that advantage?
What exactly is the benefit of using this over CRA?

**Comment by dudiharush** [comment]
Hi @saurav-bhagat. This starter will only benefit you if you want your server side in Deno, which is safer and uses Typescript by default. CRA uses NodeJS on the server.
